// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdYizFh7HY2GyReshqOsSL0sFNhU2nkhI',
    appId: '1:866787581975:web:662c28f836aefe3fddfc52',
    messagingSenderId: '866787581975',
    projectId: 'demopcps-d88d9',
    authDomain: 'demopcps-d88d9.firebaseapp.com',
    storageBucket: 'demopcps-d88d9.firebasestorage.app',
    measurementId: 'G-9P3NC0B8LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD79miydYwAce5ek6W3lcZIsbccYsjVvKk',
    appId: '1:866787581975:android:2d0ac324d7912a65ddfc52',
    messagingSenderId: '866787581975',
    projectId: 'demopcps-d88d9',
    storageBucket: 'demopcps-d88d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdYizFh7HY2GyReshqOsSL0sFNhU2nkhI',
    appId: '1:866787581975:web:9ae33a874434e18fddfc52',
    messagingSenderId: '866787581975',
    projectId: 'demopcps-d88d9',
    authDomain: 'demopcps-d88d9.firebaseapp.com',
    storageBucket: 'demopcps-d88d9.firebasestorage.app',
    measurementId: 'G-VDLK26Z83R',
  );
}
